
name: Deploy web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: ssh host keys
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-strict: false
          persist-credentials: true
      # using fork to setub emsdk
      - name: Setup emsdk (use cache if found, create otherwise)
        uses: agriyakhetarpal/setup-emsdk@update-to-cache-v4
        with:
          version: 4.0.6
          # cache folder, placed in the build directory,
          actions-cache-folder: 'emsdk-cache'
      - name: Build
        shell: bash
        run: |
          CXX=em++ CC=emcc make -j $(nproc)
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: bin/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
